### ISSUE TITLE
experiment summary view

### ISSUE THREAD

**Issue by appliedrd** [CentechMTL/TableauDeBord#38]
view of experiments over all companies 
num in progress
num validitated
last experiment update

**Comment by RignonNoel** [comment]
I can create a chart who look like the chart of KPIs in the summary for know the num in progress and the num validated.

But do you really need the last experiment update? I think it's not representative of the total experiments of the company and this take lots of place on a page because this need a complete row (or two)  in a table. 

I await your opinion before begin

**Comment by RignonNoel** [comment]
The chart look like that for the moment:

![centechtableau de bord v 1 - mozilla firefox](https://cloud.githubusercontent.com/assets/12053720/8582506/3de55c52-2595-11e5-8db3-2f0212e66905.jpg)

**Comment by MLLadmin** [comment]
when we review progress, the last update gives an idea of when the company did their 'mis a jour'. tjust something I usally look at when monitoring. If it takes too much room, you can remove

**Comment by RignonNoel** [comment]
Oh sorry, it's me...
I understood "last experiment updated" and not "last experiment update".

The last experiment update is a good point and i've already put it in the chart.

**Comment by appliedrd** [comment]
good.
