### ISSUE TITLE
show incubation start & end  date per company (plus months in incubation)

### ISSUE THREAD

**Issue by appliedrd** [CentechMTL/TableauDeBord#44]

**Comment by RignonNoel** [comment]
We are now a timeline with a percentage of the time of incubation spent.
We are the date of incubation just in top of this timelne.

**Comment by RignonNoel** [comment]
For test, you just need set a date of incubation on a company. 
To do that:
- Go on the detail page of a company
- Click on the link on the top of the page "modify this company"
- Set a date of incubation
- Save the form

The time of incubation is 3 years.

**Comment by appliedrd** [comment]
Incubation phase : Emergence Mai 2015 
should be
Incubation phase : Emergence
start date: Mai 2015 (0 years 2 months)
end date:

**Comment by RignonNoel** [comment]
This is the new display :
![centechtableau de bord v 1 - mozilla firefox](https://cloud.githubusercontent.com/assets/12053720/8985174/e90f5028-36a3-11e5-858e-299f4b271f0f.jpg)

The incubation phase is Emergence Mai 2015 because we have decided to keep the status of a company.

We have no "cohort", just a status. So the module of presence and all other module based on a "group" of company is based on the status.

So we will have 'Emergence Mai 2015', 'Emergence Aout 2015', etc..

If you want change that, it's possible but we need to discuss about that seriously before i begin.

**Comment by RignonNoel** [comment]
Oh.. i've forgot. I've let the percentage for the moment because initially Helene wanted a percentage. I can change that easily if you want.
